# Interface Settings (UI)
FONT_FAMILY = "Consolas"
FONT_SIZE_TITLE = 20
FONT_SIZE_SUBTITLE = 16
FONT_SIZE_TEXT = 14
FONT_SIZE_BUTTON = 14

TEXT_COLOR = "#ffffff"  # White
PRIMARY_COLOR = "#1E90FF"  # Blue
SECONDARY_COLOR = "#FF6347"  # Red

# Title Label Styles
LABEL_TITLE_STYLE = {
    "font": (FONT_FAMILY, FONT_SIZE_TITLE)
}

# Label Styles
LABEL_TITLE_STYLE = {
    "font": (FONT_FAMILY, FONT_SIZE_TEXT)
}


